coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        informational: true

ignore:
  - "cmd/"
  - "test/"
  - "examples/"
  - "docs/"
  - "**/*_test.go"
