# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  concurrency: 4

linters:
  default: none
  enable:
    # Correctness - catch real bugs
    - govet           # Reports suspicious constructs
    - staticcheck     # Comprehensive static analysis
    - errcheck        # Unchecked errors (critical for Go)
    - ineffassign     # Useless assignments
    - unused          # Unused code

    # Security
    - gosec           # Security problems

    # Code quality
    - dupl            # Code duplication

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too noisy, minor optimization

    errcheck:
      check-type-assertions: true
      check-blank: false  # Allow _ = err for intentional ignores

    gosec:
      excludes:
        - G104  # Unhandled errors (errcheck handles this)
        - G304  # File path from variable (common in CLI tools)

    dupl:
      threshold: 150

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/hlop3z/astroladb

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Relax rules for test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - dupl

    # Ignore generated code
    - path: ".*\\.pb\\.go$"
    - path: ".*\\.mock\\.go$"
