# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  tests: false
  allow-parallel-runners: true
  concurrency: 4

linters:
  default: none
  enable:
    - govet         # Suspicious constructs
    - errcheck      # Unchecked errors
    - staticcheck   # Code quality suggestions
    # TODO: Enable after cleanup
    # - unused      # Unused code

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        # Closers
        - (io.Closer).Close
        - (*os.File).Close
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        # HTTP/IO writes
        - (net/http.ResponseWriter).Write
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Printf
        - fmt.Println
        - (*encoding/json.Encoder).Encode
        # Framework-specific
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - (*github.com/dop251/goja.Runtime).Set
        - (*github.com/fsnotify/fsnotify.Watcher).Add
        - (*github.com/fsnotify/fsnotify.Watcher).Close
        - (*github.com/rivo/tview.Application).Run
        - filepath.Walk
        - os.RemoveAll
        # Error builder methods (chainable)
        - (*github.com/hlop3z/astroladb/internal/alerr.Error).With
        - (*github.com/hlop3z/astroladb/internal/alerr.Error).WithTable
        - (*github.com/hlop3z/astroladb/internal/alerr.Error).WithColumn
        - (*github.com/hlop3z/astroladb/internal/alerr.Error).WithFile
        - (*github.com/hlop3z/astroladb/internal/alerr.Error).WithLocation
        - (*github.com/hlop3z/astroladb/internal/alerr.Error).WithSource
        - (*github.com/hlop3z/astroladb/internal/alerr.Error).WithSpan
        - (*github.com/hlop3z/astroladb/internal/alerr.Error).WithNote
        - (*github.com/hlop3z/astroladb/internal/alerr.Error).WithHelp
        # Version manager
        - (*github.com/hlop3z/astroladb/internal/engine/runner.VersionManager).ReleaseLock
        # Astroladb client
        - (*github.com/hlop3z/astroladb/pkg/astroladb.Client).Close
        # DevDB
        - (*github.com/hlop3z/astroladb/internal/devdb.DevDatabase).Close
        # Internal validate
        - (*github.com/hlop3z/astroladb/internal/validate.ValidationError).With

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hlop3z/astroladb

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
