version: "3"

vars:
  BINARY_NAME: alab
  BUILD_DIR: bin
  CMD_DIR: ./cmd/alab
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo dev

tasks:
  default:
    desc: Build the project
    cmds:
      - task: build

  build:
    desc: Build binary into ./bin
    cmds:
      - echo "Building {{.BINARY_NAME}} {{.VERSION}}..."
      - mkdir -p {{.BUILD_DIR}}
      - >
        go build
        -ldflags "-s -w -X main.version={{.VERSION}}"
        -o {{.BUILD_DIR}}/{{.BINARY_NAME}}{{exeExt}}
        {{.CMD_DIR}}
      - echo "Build complete"

  build-dev:
    desc: Build and install dev binary to ~/bin
    cmds:
      - echo "Building {{.BINARY_NAME}} (dev)..."
      - mkdir -p ~/bin
      - go build -ldflags "-s -w -X main.version=dev" -o ~/bin/{{.BINARY_NAME}}{{exeExt}} {{.CMD_DIR}}
      - echo "Installed to ~/bin"

  release:
    desc: Build cross-platform release binaries
    deps: [clean]
    cmds:
      - echo "Building release {{.VERSION}}..."
      - mkdir -p {{.BUILD_DIR}}
      - GOOS=linux   GOARCH=amd64 go build -ldflags "-s -w -X main.version={{.VERSION}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-linux-amd64 {{.CMD_DIR}}
      - GOOS=darwin  GOARCH=amd64 go build -ldflags "-s -w -X main.version={{.VERSION}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-darwin-amd64 {{.CMD_DIR}}
      - GOOS=darwin  GOARCH=arm64 go build -ldflags "-s -w -X main.version={{.VERSION}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-darwin-arm64 {{.CMD_DIR}}
      - GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -X main.version={{.VERSION}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-windows-amd64.exe {{.CMD_DIR}}
      - echo "Release built"
      - ls -la {{.BUILD_DIR}}

  install:
    desc: Install using go install
    cmds:
      - echo "Installing {{.BINARY_NAME}}..."
      - go install -ldflags "-s -w -X main.version={{.VERSION}}" {{.CMD_DIR}}
      - echo "Installed to GOPATH/bin"

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  vuln:
    desc: Run govulncheck for security vulnerabilities
    cmds:
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  check:
    desc: Run all checks (lint + vuln + test)
    cmds:
      - task: lint
      - task: vuln
      - task: test

  test:
    desc: Run tests (without race detector)
    cmds:
      - go test ./...

  test-race:
    desc: Run tests with race detector (requires gcc)
    cmds:
      - CGO_ENABLED=1 go test -race ./...

  setup:
    desc: Install dev tools (lefthook, golangci-lint)
    cmds:
      - go install github.com/evilmartians/lefthook@latest
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
      - lefthook install

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  # Recording tasks
  record-build:
    desc: Build the CLI recorder Docker image
    cmds:
      - docker build -t alab-recorder -f scripts/recorder/Dockerfile .

  record:
    desc: "Record a CLI scenario to GIF (usage: task record SCENARIO=help COLS=140)"
    cmds:
      - mkdir -p docs/gifs
      - 'docker run --rm -e COLS={{.COLS | default "140"}} -v "{{.ROOT_DIR}}/docs/gifs:/output" alab-recorder {{.SCENARIO | default "help"}}'

  record-all:
    desc: Record all available scenarios
    cmds:
      - mkdir -p docs/gifs
      - docker run --rm -v "{{.ROOT_DIR}}/docs/gifs:/output" alab-recorder help
      - docker run --rm -v "{{.ROOT_DIR}}/docs/gifs:/output" alab-recorder init
      - docker run --rm -v "{{.ROOT_DIR}}/docs/gifs:/output" alab-recorder workflow
      - docker run --rm -e COLS=180 -v "{{.ROOT_DIR}}/docs/gifs:/output" alab-recorder status
      - docker run --rm -v "{{.ROOT_DIR}}/docs/gifs:/output" alab-recorder export
      - docker run --rm -v "{{.ROOT_DIR}}/docs/gifs:/output" alab-recorder live-openapi
      - echo "All recordings saved to docs/gifs/"

  record-list:
    desc: List available recording scenarios
    cmds:
      - ls -1 scripts/recorder/scenarios/*.sh | xargs -I{} basename {} .sh

  # Database tasks for integration/e2e testing
  db-up:
    desc: Start test databases (PostgreSQL, CockroachDB, Gitea)
    cmds:
      - docker compose -f docker-compose.test.yml up -d --wait
      - echo "Test databases ready."

  db-down:
    desc: Stop test databases
    cmds:
      - docker compose -f docker-compose.test.yml down

  test-integration:
    desc: Run integration tests (starts/stops Docker databases)
    cmds:
      - task: db-up
      - defer: { task: db-down }
      - go test ./... -tags=integration -count=1

  test-all:
    desc: Run all tests including e2e (starts/stops Docker databases)
    cmds:
      - task: db-up
      - defer: { task: db-down }
      - go test ./... -tags=integration,e2e -count=1
