version: "3"

vars:
  BINARY_NAME: alab
  BUILD_DIR: bin
  CMD_DIR: ./cmd/alab
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo dev

tasks:
  default:
    desc: Build the project
    cmds:
      - task: build

  build:
    desc: Build binary into ./bin
    cmds:
      - echo "Building {{.BINARY_NAME}} {{.VERSION}}..."
      - mkdir -p {{.BUILD_DIR}}
      - >
        go build
        -ldflags "-s -w -X main.version={{.VERSION}}"
        -o {{.BUILD_DIR}}/{{.BINARY_NAME}}{{exeExt}}
        {{.CMD_DIR}}
      - echo "Build complete"

  build-dev:
    desc: Build and install dev binary to ~/bin
    cmds:
      - echo "Building {{.BINARY_NAME}} (dev)..."
      - mkdir -p ~/bin
      - go build -ldflags "-s -w -X main.version=dev" -o ~/bin/{{.BINARY_NAME}}{{exeExt}} {{.CMD_DIR}}
      - echo "Installed to ~/bin"

  release:
    desc: Build cross-platform release binaries
    deps: [clean]
    cmds:
      - echo "Building release {{.VERSION}}..."
      - mkdir -p {{.BUILD_DIR}}
      - GOOS=linux   GOARCH=amd64 go build -ldflags "-s -w -X main.version={{.VERSION}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-linux-amd64 {{.CMD_DIR}}
      - GOOS=darwin  GOARCH=amd64 go build -ldflags "-s -w -X main.version={{.VERSION}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-darwin-amd64 {{.CMD_DIR}}
      - GOOS=darwin  GOARCH=arm64 go build -ldflags "-s -w -X main.version={{.VERSION}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-darwin-arm64 {{.CMD_DIR}}
      - GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -X main.version={{.VERSION}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-windows-amd64.exe {{.CMD_DIR}}
      - echo "Release built"
      - ls -la {{.BUILD_DIR}}

  install:
    desc: Install using go install
    cmds:
      - echo "Installing {{.BINARY_NAME}}..."
      - go install -ldflags "-s -w -X main.version={{.VERSION}}" {{.CMD_DIR}}
      - echo "Installed to GOPATH/bin"

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  vuln:
    desc: Run govulncheck for security vulnerabilities
    cmds:
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  check:
    desc: Run all checks (lint + vuln + test)
    cmds:
      - task: lint
      - task: vuln
      - task: test

  test:
    desc: Run tests (without race detector)
    cmds:
      - go test ./...

  test-race:
    desc: Run tests with race detector (requires gcc)
    cmds:
      - CGO_ENABLED=1 go test -race ./...

  setup:
    desc: Install dev tools (lefthook, golangci-lint)
    cmds:
      - go install github.com/evilmartians/lefthook@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - lefthook install

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
