// FastAPI Code Generator (v2 - Clean Templates)
// Generates Pydantic models and CRUD routers from your alab schema.
//
// Usage:
//   alab gen run generators/fastapi -o ./generated

export default gen((schema) => {
  const files = {};

  // ─── Helpers ───────────────────────────────────────────────

  const capitalize = (s) => s.charAt(0).toUpperCase() + s.slice(1);
  const pascalCase = (s) => s.split("_").map(capitalize).join("");

  const TYPE_MAP = {
    uuid: "UUID",
    string: "str",
    text: "str",
    integer: "int",
    float: "float",
    boolean: "bool",
    date: "date",
    time: "time",
    datetime: "datetime",
    decimal: "Decimal",
    json: "dict",
    base64: "str",
  };

  const pyType = (col) => {
    if (col.type === "enum" && col.enum) return `${capitalize(col.name)}Enum`;
    return TYPE_MAP[col.type] || "Any";
  };

  const pyDefault = (col) => {
    const def = col.default;
    if (def === undefined || typeof def === "object") return "";
    const pt = pyType(col);
    if (col.type === "enum") return ` = ${pt}.${String(def).toUpperCase()}`;
    if (typeof def === "boolean") return ` = ${def ? "True" : "False"}`;
    if (typeof def === "string") return ` = "${def}"`;
    if (col.type === "decimal") return ` = Decimal("${def}")`;
    return ` = ${def}`;
  };

  const pyField = (col) => {
    const pt = pyType(col);
    if (col.nullable) return `    ${col.name}: Optional[${pt}] = None`;
    return `    ${col.name}: ${pt}${pyDefault(col)}`;
  };

  // ─── Templates ─────────────────────────────────────────────

  const modelFile = (tables) => {
    const models = tables.map((table) => {
      const cls = pascalCase(table.name);
      const fields = table.columns
        .filter((c) => !["id", "created_at", "updated_at"].includes(c.name))
        .map(pyField);

      const enums = table.columns
        .filter((col) => col.type === "enum" && col.enum)
        .map((col) => {
          const enumName = `${capitalize(col.name)}Enum`;
          const values = col.enum
            .map((val) => `    ${val.toUpperCase()} = "${val}"`)
            .join("\n");
          return `\nclass ${enumName}(str, Enum):\n${values}\n`;
        })
        .join("");

      const baseFields = fields.length > 0 ? fields.join("\n") : "    pass";

      return `${enums}
class ${cls}Base(BaseModel):
${baseFields}


class ${cls}(${cls}Base):
    id: UUID
${table.timestamps ? "    created_at: datetime\n    updated_at: datetime\n" : ""}
    class Config:
        from_attributes = True
`.trim();
    }).join("\n\n");

    return `
from __future__ import annotations

from datetime import date, time, datetime
from decimal import Decimal
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel

${models}
`.trim() + "\n";
  };

  const routerFile = (ns, tables) => {
    const imports = tables
      .map((t) => `    ${pascalCase(t.name)},\n    ${pascalCase(t.name)}Base,`)
      .join("\n");

    const routers = tables.map((table) => {
      const cls = pascalCase(table.name);
      const slug = table.name.replace(/_/g, "-");

      return `
@router.get("/${slug}")
async def list_${table.name}():
    # TODO: implement
    raise HTTPException(501, "not implemented")


@router.get("/${slug}/{item_id}")
async def get_${table.name}(item_id: UUID):
    # TODO: implement
    raise HTTPException(501, "not implemented")


@router.post("/${slug}", response_model=${cls}, status_code=201)
async def create_${table.name}(body: ${cls}Base):
    # TODO: implement
    raise HTTPException(501, "not implemented")


@router.patch("/${slug}/{item_id}", response_model=${cls})
async def update_${table.name}(item_id: UUID, body: ${cls}Base):
    # TODO: implement
    raise HTTPException(501, "not implemented")


@router.delete("/${slug}/{item_id}", status_code=204)
async def delete_${table.name}(item_id: UUID):
    # TODO: implement
    raise HTTPException(501, "not implemented")
`.trim();
    }).join("\n\n\n");

    return `
from __future__ import annotations

from uuid import UUID

from fastapi import APIRouter, HTTPException

from .models import (
${imports}
)


router = APIRouter(prefix="/${ns}", tags=["${ns}"])


${routers}
`.trim() + "\n";
  };

  const mainFile = (namespaces) => {
    const imports = namespaces
      .map((ns) => `from ${ns} import router as ${ns}_router`)
      .join("\n");
    const routers = namespaces
      .map((ns) => `app.include_router(${ns}_router)`)
      .join("\n");

    return `
"""
FastAPI app (generated by alab).

Run:
    uv run fastapi dev main.py

Then open http://localhost:8000/docs
"""

from fastapi import FastAPI

${imports}

app = FastAPI(title="Alab Generated API")

${routers}


@app.get("/")
async def root():
    return {"message": "Alab Generated API", "docs": "/docs"}
`.trim() + "\n";
  };

  // ─── Generate ──────────────────────────────────────────────

  for (const [ns, tables] of Object.entries(schema.models)) {
    files[`${ns}/models.py`] = modelFile(tables);
    files[`${ns}/router.py`] = routerFile(ns, tables);
    files[`${ns}/__init__.py`] = "from .router import router  # noqa: F401\n";
  }

  files["main.py"] = mainFile(Object.keys(schema.models));

  return render(files);
});
