// Package types provides generated Go types from the database schema.
// Generated by: alab export --format go
package types

type AuthUser struct {
	Age        *int32   `json:"age,omitempty"`
	Avatar     *string  `json:"avatar,omitempty"`
	Balance    string   `json:"balance"`
	Bio        *string  `json:"bio,omitempty"`
	Birthdate  *string  `json:"birthdate,omitempty"`
	ExternalId *string  `json:"external_id,omitempty"`
	Id         string   `json:"id"`
	IsActive   bool     `json:"is_active"`
	LastSeen   *string  `json:"last_seen,omitempty"`
	LoginTime  *string  `json:"login_time,omitempty"`
	Role       string   `json:"role"`
	Score      *float32 `json:"score,omitempty"`
	Settings   *any     `json:"settings,omitempty"`
	Username   string   `json:"username"`
	CreatedAt  string   `json:"created_at"`
	UpdatedAt  string   `json:"updated_at"`
}

// TYPES maps schema URIs to type names.
var TYPES = map[string]string{
	"auth.user": "AuthUser",
}
